### ISSUE TITLE
SIL Gen?

### ISSUE THREAD

**Issue by markmals** [theblixguy/LittleSwift#1]
Are there any plans to integrate a SIL generation step? Where would that step fit into the current compiler process?

I mainly ask because I'm interested in possibly using LittleSwift as a backend to transpile Swift to JavaScript at some point in the future ([by lowering SIL to JavaScript without going through LLVM at all](https://bugs.swift.org/browse/SR-9307?focusedCommentId=42512&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-42512)) and SIL gen seems like one of the features that would be need to be implemented before that could happen.

**Comment by theblixguy** [comment]
Hi Mark,

I think such a step can be put after the type checking phase. Generating raw SIL shouldn’t be _too_ difficult (the Swift compiler does it by walking the type checked AST and emitting raw SIL), however generating canonical SIL would mean re-implementing a lot of optimisation passes. We could always generate raw SIL and pass it to swiftc so it can do this for us, but doing it from scratch in Swift is going to take a lot of work and you would definitely need canonical SIL if you want to use SIL for transpilation! 

If you’re interested to learn more about SIL, there’s a [document](https://github.com/apple/swift/blob/master/docs/SIL.rst) on it which could be helpful.

**Comment by theblixguy** [comment]
Wouldn’t it be possible to use the LLVM IR for this? 

You could also design your own backend that generates JavaScript code from the AST. LittleSwift already does this to emit Kotlin code (it’s pretty basic and a bit hack-y, but you could use the same idea to emit the code in a different language).

**Comment by markmals** [comment]
> You could also design your own backend that generates JavaScript code from the AST

Definitely. I was mainly asking about SIL because of @jckarter's comment on [that Swift bug](https://bugs.swift.org/browse/SR-9307?focusedCommentId=42512&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-42512). I thought that perhaps SIL might be better for transpilation purposes than the raw Swift AST, but maybe there's not too many benefits of one over the other.

This is one of the things I've been wanting to explore a lot more in-depth, since I think there is tons of opportunity for transpiling Swift to other high-level and low-level languages (Java bytecode comes to mind), as inspired by the recent developments with WebAssembly in `swiftc`. 

> Wouldn’t it be possible to use the LLVM IR for this?

I'm not exactly sure how one would do this and AFAIK there's no built-in way to lower LLVM IR to JavaScript, like there is to lower LLVM IR to WebAssembly. Someone could probably write a module to do it, but I suspect that SIL maps to JavaScript better than LLVM IR, since it's higher level.

I'm going to do some research over the next few months as I ponder and work on these issues and see what I can figure out. I'll lay my current thoughts out here for posterity, going forward. The options we could consider for such a process are:

* Generating raw SIL, feeding it to `swiftc` for optimization passes, and lowering the canonical SIL to JavaScript afterwards with a custom SIL → JS `lswiftc` module
* Using some other method — like the [`Emitter`](https://github.com/theblixguy/LittleSwift/tree/master/Sources/LittleSwift/Emitter) protocol — to derive JavaScript code from the Swift AST
* Writing an `lswiftc` module to lower LLVM IR to JavaScript directly
